coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        informational: true   # report only; do not fail build or turn red when below target
    patch:
      default:
        target: 90%
        threshold: 1%
        informational: true   # report only; do not fail build or turn red when below target