from __future__ import annotations

from enum import Enum


# PII Types and Models as expanded in research
# Research Page:
# AWS Comprehend PII Docs: https://docs.aws.amazon.com/comprehend/latest/dg/how-pii.html


class AWSComprehendPIIType(Enum):
    """
    AWS Comprehend-Supported PII types
    """

    EMAIL_ADDRESS = "EMAIL"
    ADDRESS = "ADDRESS"
    PERSON = "NAME"
    PHONE_NUMBER = "PHONE"
    DATE = "DATE_TIME"
    URL = "URL"
    AGE = "AGE"
    USERNAME = "USERNAME"
    PASSWORD = "PASSWORD"
    CREDIT_DEBIT_NUMBER = "CREDIT_DEBIT_NUMBER"
    CREDIT_DEBIT_CVV = "CREDIT_DEBIT_CVV"
    CREDIT_DEBIT_EXPIRY = "CREDIT_DEBIT_EXPIRY"
    PIN = "PIN"
    US_DRIVERS_LICENSE_NUMBER = "DRIVER_ID"
    LICENSE_PLATE_NUMBER = "LICENSE_PLATE"
    VEHICLE_IDENTIFICATION_NUMBER = "VEHICLE_IDENTIFICATION_NUMBER"
    INTERNATIONAL_BANKING_ACCOUNT_NUMBER = "INTERNATIONAL_BANK_ACCOUNT_NUMBER"
    SWIFT_CODE = "SWIFT_CODE"
    CRYPTO = "CRYPTO_WALLET_ADDRESS"
    IP_ADDRESS = "IP_ADDRESS"
    IPV6_ADDRESS = "IPV6_ADDRESS"
    MAC_ADDRESS = "MAC_ADDRESS"
    AWS_ACCESS_KEY = "AWS_ACCESS_KEY"
    AWS_SECRET_KEY = "AWS_SECRET_KEY"
    US_PASSPORT_NUMBER = "PASSPORT_NUMBER"
    US_SOCIAL_SECURITY_NUMBER = "SSN"
    US_BANK_ACCOUNT_NUMBER = "BANK_ACCOUNT_NUMBER"
    ABA_ROUTING_NUMBER = "BANK_ROUTING"
    US_INDIVIDUAL_TAXPAYER_IDENTIFICATION = "US_INDIVIDUAL_TAXPAYER_IDENTIFICATION"
    UK_NATIONAL_HEALTH_SERVICE_NUMBER = "UK_NATIONAL_HEALTH_SERVICE_NUMBER"
    UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER = "UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER"
    UK_NATIONAL_INSURANCE_NUMBER = "UK_NATIONAL_INSURANCE_NUMBER"
    CA_HEALTH_NUMBER = "CA_HEALTH_NUMBER"
    CA_SOCIAL_INSURANCE_NUMBER = "CA_SOCIAL_INSURANCE_NUMBER"
    IN_AADHAAR = "IN_AADHAAR"
    IN_VOTER_NUMBER = "IN_VOTER_NUMBER"
    IN_PERMANENT_ACCOUNT_NUMBER = "IN_PERMANENT_ACCOUNT_NUMBER"
    IN_NREGA = "IN_NREGA"
    ALL = "ALL"
