from __future__ import annotations

from enum import Enum


# Azure PII Types
# Research Page:
# https://azuresdkdocs.blob.core.windows.net/$web/python/azure-ai-textanalytics/latest/
# azure.ai.textanalytics.html#azure.ai.textanalytics.TextAnalyticsClient.recognize_pii_entities


class AzureDetectionType(Enum):
    """
    Azure-supported PII Types: The values fed into the Azure service for detection
    """

    ABA_ROUTING_NUMBER = "ABARoutingNumber"
    ADDRESS = "Address"
    AGE = "Age"
    AR_NATIONAL_IDENTITY_NUMBER = "ARNationalIdentityNumber"
    AT_IDENTITY_CARD = "ATIdentityCard"
    AT_TAX_IDENTIFICATION_NUMBER = "ATTaxIdentificationNumber"
    AT_VALUE_ADDED_TAX_NUMBER = "ATValueAddedTaxNumber"
    AU_BANK_ACCOUNT_NUMBER = "AUBankAccountNumber"
    AU_BUSINESS_NUMBER = "AUBusinessNumber"
    AU_COMPANY_NUMBER = "AUCompanyNumber"
    AU_DRIVERS_LICENSE_NUMBER = "AUDriversLicenseNumber"
    AU_MEDICAL_ACCOUNT_NUMBER = "AUMedicalAccountNumber"
    AU_PASSPORT_NUMBER = "AUPassportNumber"
    AU_TAX_FILE_NUMBER = "AUTaxFileNumber"
    AZURE_DOCUMENT_DB_AUTH_KEY = "AzureDocumentDBAuthKey"
    AZURE_IAAS_DATABASE_CONNECTION_AND_SQL_STRING = (
        "AzureIAASDatabaseConnectionAndSQLString"
    )
    AZURE_IO_T_CONNECTION_STRING = "AzureIoTConnectionString"
    AZURE_PUBLISH_SETTING_PASSWORD = "AzurePublishSettingPassword"
    AZURE_REDIS_CACHE_STRING = "AzureRedisCacheString"
    AZURE_SAS = "AzureSAS"
    AZURE_SERVICE_BUS_STRING = "AzureServiceBusString"
    AZURE_STORAGE_ACCOUNT_GENERIC = "AzureStorageAccountGeneric"
    AZURE_STORAGE_ACCOUNT_KEY = "AzureStorageAccountKey"
    BE_NATIONAL_NUMBER = "BENationalNumber"
    BE_NATIONAL_NUMBER_V2 = "BENationalNumberV2"
    BE_VALUE_ADDED_TAX_NUMBER = "BEValueAddedTaxNumber"
    BG_UNIFORM_CIVIL_NUMBER = "BGUniformCivilNumber"
    BRCPF_NUMBER = "BRCPFNumber"
    BR_LEGAL_ENTITY_NUMBER = "BRLegalEntityNumber"
    BR_NATIONAL_IDRG = "BRNationalIDRG"
    CA_BANK_ACCOUNT_NUMBER = "CABankAccountNumber"
    CA_DRIVERS_LICENSE_NUMBER = "CADriversLicenseNumber"
    CA_HEALTH_SERVICE_NUMBER = "CAHealthServiceNumber"
    CA_PASSPORT_NUMBER = "CAPassportNumber"
    CA_PERSONAL_HEALTH_IDENTIFICATION = "CAPersonalHealthIdentification"
    CA_SOCIAL_INSURANCE_NUMBER = "CASocialInsuranceNumber"
    CH_SOCIAL_SECURITY_NUMBER = "CHSocialSecurityNumber"
    CL_IDENTITY_CARD_NUMBER = "CLIdentityCardNumber"
    CN_RESIDENT_IDENTITY_CARD_NUMBER = "CNResidentIdentityCardNumber"
    CREDIT_CARD_NUMBER = "CreditCardNumber"
    CY_IDENTITY_CARD = "CYIdentityCard"
    CY_TAX_IDENTIFICATION_NUMBER = "CYTaxIdentificationNumber"
    CZ_PERSONAL_IDENTITY_NUMBER = "CZPersonalIdentityNumber"
    CZ_PERSONAL_IDENTITY_V2 = "CZPersonalIdentityV2"
    DATE = "Date"
    DEFAULT = "Default"
    DE_DRIVERS_LICENSE_NUMBER = "DEDriversLicenseNumber"
    DE_IDENTITY_CARD_NUMBER = "DEIdentityCardNumber"
    DE_PASSPORT_NUMBER = "DEPassportNumber"
    DE_TAX_IDENTIFICATION_NUMBER = "DETaxIdentificationNumber"
    DE_VALUE_ADDED_NUMBER = "DEValueAddedNumber"
    DK_PERSONAL_IDENTIFICATION_NUMBER = "DKPersonalIdentificationNumber"
    DK_PERSONAL_IDENTIFICATION_V2 = "DKPersonalIdentificationV2"
    DRUG_ENFORCEMENT_AGENCY_NUMBER = "DrugEnforcementAgencyNumber"
    EE_PERSONAL_IDENTIFICATION_CODE = "EEPersonalIdentificationCode"
    EMAIL_ADDRESS = "Email"
    ES_DNI = "ESDNI"
    ES_SOCIAL_SECURITY_NUMBER = "ESSocialSecurityNumber"
    ES_TAX_IDENTIFICATION_NUMBER = "ESTaxIdentificationNumber"
    EUGPS_COORDINATES = "EUGPSCoordinates"
    EU_DEBIT_CARD_NUMBER = "EUDebitCardNumber"
    EU_DRIVERS_LICENSE_NUMBER = "EUDriversLicenseNumber"
    EU_NATIONAL_IDENTIFICATION_NUMBER = "EUNationalIdentificationNumber"
    EU_PASSPORT_NUMBER = "EUPassportNumber"
    EU_SOCIAL_SECURITY_NUMBER = "EUSocialSecurityNumber"
    EU_TAX_IDENTIFICATION_NUMBER = "EUTaxIdentificationNumber"
    FI_EUROPEAN_HEALTH_NUMBER = "FIEuropeanHealthNumber"
    FI_NATIONAL_ID = "FINationalID"
    FI_NATIONAL_IDV2 = "FINationalIDV2"
    FI_PASSPORT_NUMBER = "FIPassportNumber"
    FR_DRIVERS_LICENSE_NUMBER = "FRDriversLicenseNumber"
    FR_HEALTH_INSURANCE_NUMBER = "FRHealthInsuranceNumber"
    FR_NATIONAL_ID = "FRNationalID"
    FR_PASSPORT_NUMBER = "FRPassportNumber"
    FR_SOCIAL_SECURITY_NUMBER = "FRSocialSecurityNumber"
    FR_TAX_IDENTIFICATION_NUMBER = "FRTaxIdentificationNumber"
    FR_VALUE_ADDED_TAX_NUMBER = "FRValueAddedTaxNumber"
    GR_NATIONAL_IDV2 = "GRNationalIDV2"
    GR_NATIONAL_ID_CARD = "GRNationalIDCard"
    GR_TAX_IDENTIFICATION_NUMBER = "GRTaxIdentificationNumber"
    HK_IDENTITY_CARD_NUMBER = "HKIdentityCardNumber"
    HR_IDENTITY_CARD_NUMBER = "HRIdentityCardNumber"
    HR_NATIONAL_ID_NUMBER = "HRNationalIDNumber"
    HR_PERSONAL_IDENTIFICATION_NUMBER = "HRPersonalIdentificationNumber"
    HR_PERSONAL_IDENTIFICATION_OIB_NUMBER_V2 = "HRPersonalIdentificationOIBNumberV2"
    HU_PERSONAL_IDENTIFICATION_NUMBER = "HUPersonalIdentificationNumber"
    HU_TAX_IDENTIFICATION_NUMBER = "HUTaxIdentificationNumber"
    HU_VALUE_ADDED_NUMBER = "HUValueAddedNumber"
    ID_IDENTITY_CARD_NUMBER = "IDIdentityCardNumber"
    IE_PERSONAL_PUBLIC_SERVICE_NUMBER = "IEPersonalPublicServiceNumber"
    IE_PERSONAL_PUBLIC_SERVICE_NUMBER_V2 = "IEPersonalPublicServiceNumberV2"
    IL_BANK_ACCOUNT_NUMBER = "ILBankAccountNumber"
    IL_NATIONAL_ID = "ILNationalID"
    INTERNATIONAL_BANKING_ACCOUNT_NUMBER = "InternationalBankingAccountNumber"
    IN_PERMANENT_ACCOUNT = "INPermanentAccount"
    IN_UNIQUE_IDENTIFICATION_NUMBER = "INUniqueIdentificationNumber"
    IP_ADDRESS = "IPAddress"
    IT_DRIVERS_LICENSE_NUMBER = "ITDriversLicenseNumber"
    IT_FISCAL_CODE = "ITFiscalCode"
    IT_VALUE_ADDED_TAX_NUMBER = "ITValueAddedTaxNumber"
    JP_BANK_ACCOUNT_NUMBER = "JPBankAccountNumber"
    JP_DRIVERS_LICENSE_NUMBER = "JPDriversLicenseNumber"
    JP_MY_NUMBER_CORPORATE = "JPMyNumberCorporate"
    JP_MY_NUMBER_PERSONAL = "JPMyNumberPersonal"
    JP_PASSPORT_NUMBER = "JPPassportNumber"
    JP_RESIDENCE_CARD_NUMBER = "JPResidenceCardNumber"
    JP_RESIDENT_REGISTRATION_NUMBER = "JPResidentRegistrationNumber"
    JP_SOCIAL_INSURANCE_NUMBER = "JPSocialInsuranceNumber"
    KR_RESIDENT_REGISTRATION_NUMBER = "KRResidentRegistrationNumber"
    LT_PERSONAL_CODE = "LTPersonalCode"
    LU_NATIONAL_IDENTIFICATION_NUMBER_NATURAL = "LUNationalIdentificationNumberNatural"
    LU_NATIONAL_IDENTIFICATION_NUMBER_NON_NATURAL = (
        "LUNationalIdentificationNumberNonNatural"
    )
    LV_PERSONAL_CODE = "LVPersonalCode"
    MT_IDENTITY_CARD_NUMBER = "MTIdentityCardNumber"
    MT_TAX_ID_NUMBER = "MTTaxIDNumber"
    MY_IDENTITY_CARD_NUMBER = "MYIdentityCardNumber"
    NL_CITIZENS_SERVICE_NUMBER = "NLCitizensServiceNumber"
    NL_CITIZENS_SERVICE_NUMBER_V2 = "NLCitizensServiceNumberV2"
    NL_TAX_IDENTIFICATION_NUMBER = "NLTaxIdentificationNumber"
    NL_VALUE_ADDED_TAX_NUMBER = "NLValueAddedTaxNumber"
    NO_IDENTITY_NUMBER = "NOIdentityNumber"
    NZ_BANK_ACCOUNT_NUMBER = "NZBankAccountNumber"
    NZ_DRIVERS_LICENSE_NUMBER = "NZDriversLicenseNumber"
    NZ_INLAND_REVENUE_NUMBER = "NZInlandRevenueNumber"
    NZ_MINISTRY_OF_HEALTH_NUMBER = "NZMinistryOfHealthNumber"
    NZ_SOCIAL_WELFARE_NUMBER = "NZSocialWelfareNumber"
    ORGANIZATION = "Organization"
    PERSON = "Person"
    PHONE_NUMBER = "PhoneNumber"
    PH_UNIFIED_MULTI_PURPOSE_ID_NUMBER = "PHUnifiedMultiPurposeIDNumber"
    PLREGON_NUMBER = "PLREGONNumber"
    PL_IDENTITY_CARD = "PLIdentityCard"
    PL_NATIONAL_ID = "PLNationalID"
    PL_NATIONAL_IDV2 = "PLNationalIDV2"
    PL_PASSPORT_NUMBER = "PLPassportNumber"
    PL_TAX_IDENTIFICATION_NUMBER = "PLTaxIdentificationNumber"
    PT_CITIZEN_CARD_NUMBER = "PTCitizenCardNumber"
    PT_CITIZEN_CARD_NUMBER_V2 = "PTCitizenCardNumberV2"
    PT_TAX_IDENTIFICATION_NUMBER = "PTTaxIdentificationNumber"
    RO_PERSONAL_NUMERICAL_CODE = "ROPersonalNumericalCode"
    RU_PASSPORT_NUMBER_DOMESTIC = "RUPassportNumberDomestic"
    RU_PASSPORT_NUMBER_INTERNATIONAL = "RUPassportNumberInternational"
    SA_NATIONAL_ID = "SANationalID"
    SE_NATIONAL_ID = "SENationalID"
    SE_NATIONAL_IDV2 = "SENationalIDV2"
    SE_PASSPORT_NUMBER = "SEPassportNumber"
    SE_TAX_IDENTIFICATION_NUMBER = "SETaxIdentificationNumber"
    SG_NATIONAL_REGISTRATION_IDENTITY_CARD_NUMBER = (
        "SGNationalRegistrationIdentityCardNumber"
    )
    SI_TAX_IDENTIFICATION_NUMBER = "SITaxIdentificationNumber"
    SI_UNIQUE_MASTER_CITIZEN_NUMBER = "SIUniqueMasterCitizenNumber"
    SK_PERSONAL_NUMBER = "SKPersonalNumber"
    SQL_SERVER_CONNECTION_STRING = "SQLServerConnectionString"
    SWIFT_CODE = "SWIFTCode"
    TH_POPULATION_IDENTIFICATION_CODE = "THPopulationIdentificationCode"
    TR_NATIONAL_IDENTIFICATION_NUMBER = "TRNationalIdentificationNumber"
    TW_NATIONAL_ID = "TWNationalID"
    TW_PASSPORT_NUMBER = "TWPassportNumber"
    TW_RESIDENT_CERTIFICATE = "TWResidentCertificate"
    UA_PASSPORT_NUMBER_DOMESTIC = "UAPassportNumberDomestic"
    UA_PASSPORT_NUMBER_INTERNATIONAL = "UAPassportNumberInternational"
    UK_DRIVERS_LICENSE_NUMBER = "UKDriversLicenseNumber"
    UK_ELECTORAL_ROLL_NUMBER = "UKElectoralRollNumber"
    UK_NATIONAL_HEALTH_NUMBER = "UKNationalHealthNumber"
    UK_NATIONAL_INSURANCE_NUMBER = "UKNationalInsuranceNumber"
    UK_UNIQUE_TAXPAYER_NUMBER = "UKUniqueTaxpayerNumber"
    URL = "URL"
    USUK_PASSPORT_NUMBER = "USUKPassportNumber"
    US_BANK_ACCOUNT_NUMBER = "USBankAccountNumber"
    US_DRIVERS_LICENSE_NUMBER = "USDriversLicenseNumber"
    US_INDIVIDUAL_TAXPAYER_IDENTIFICATION = "USIndividualTaxpayerIdentification"
    US_SOCIAL_SECURITY_NUMBER = "USSocialSecurityNumber"
    ZA_IDENTIFICATION_NUMBER = "ZAIdentificationNumber"
    ALL = "All"


class AzurePIIType(Enum):
    """
    Azure-supported PII Types: The values of types returned from the Azure Cognition PII Detection API
    """

    ABA_ROUTING_NUMBER = "ABA Routing Number"
    ADDRESS = "Address"
    AGE = "Age"
    AR_NATIONAL_IDENTITY_NUMBER = "AR National Identity Number"
    AT_IDENTITY_CARD = "ATIdentityCard"
    AT_TAX_IDENTIFICATION_NUMBER = "AT Tax Identification Number"
    AT_VALUE_ADDED_TAX_NUMBER = "AT Value Added Tax Number"
    AU_BANK_ACCOUNT_NUMBER = "AU Bank Account Number"
    AU_BUSINESS_NUMBER = "AU Business Number"
    AU_COMPANY_NUMBER = "AU Company Number"
    AU_DRIVERS_LICENSE_NUMBER = "AU Drivers License Number"
    AU_MEDICAL_ACCOUNT_NUMBER = "AU Medical Account Number"
    AU_PASSPORT_NUMBER = "AU Passport Number"
    AU_TAX_FILE_NUMBER = "AU Tax File Number"
    AZURE_DOCUMENT_DB_AUTH_KEY = "Azure Document DB Auth Key"
    AZURE_IAAS_DATABASE_CONNECTION_AND_SQL_STRING = (
        "Azure IAAS Database Connection And SQL String"
    )
    AZURE_IO_T_CONNECTION_STRING = "Azure IoT Connection String"
    AZURE_PUBLISH_SETTING_PASSWORD = "Azure Publish Setting Password"
    AZURE_REDIS_CACHE_STRING = "Azure Redis Cache String"
    AZURE_SAS = "Azure SAS"
    AZURE_SERVICE_BUS_STRING = "Azure Service Bus String"
    AZURE_STORAGE_ACCOUNT_GENERIC = "Azure Storage Account Generic"
    AZURE_STORAGE_ACCOUNT_KEY = "Azure Storage Account Key"
    BE_NATIONAL_NUMBER = "BE National Number"
    BE_NATIONAL_NUMBER_V2 = "BE National Number V2"
    BE_VALUE_ADDED_TAX_NUMBER = "BE Value Added Tax Number"
    BG_UNIFORM_CIVIL_NUMBER = "BG Uniform Civil Number"
    BRCPF_NUMBER = "BR CPF Number"
    BR_LEGAL_ENTITY_NUMBER = "BR Legal Entity Number"
    BR_NATIONAL_IDRG = "BR National IDRG"
    CA_BANK_ACCOUNT_NUMBER = "CA Bank Account Number"
    CA_DRIVERS_LICENSE_NUMBER = "CA Drivers License Number"
    CA_HEALTH_SERVICE_NUMBER = "CA Health Service Number"
    CA_PASSPORT_NUMBER = "CA Passport Number"
    CA_PERSONAL_HEALTH_IDENTIFICATION = "CA Personal Health Identification"
    CA_SOCIAL_INSURANCE_NUMBER = "CA Social Insuranc eNumber"
    CH_SOCIAL_SECURITY_NUMBER = "CH Social Security Number"
    CL_IDENTITY_CARD_NUMBER = "CL Identity Card Number"
    CN_RESIDENT_IDENTITY_CARD_NUMBER = "CN Resident Identity Card Number"
    CREDIT_CARD_NUMBER = "Credit Card Number"
    CY_IDENTITY_CARD = "CY Identity Card"
    CY_TAX_IDENTIFICATION_NUMBER = "CY Tax Identification Number"
    CZ_PERSONAL_IDENTITY_NUMBER = "CZ Personal Identity Number"
    CZ_PERSONAL_IDENTITY_V2 = "CZ Personal Identity V2"
    DATE = "Date"
    DEFAULT = "Default"
    DE_DRIVERS_LICENSE_NUMBER = "DE Drivers License Number"
    DE_IDENTITY_CARD_NUMBER = "DE Identity Card Number"
    DE_PASSPORT_NUMBER = "DE Passport Number"
    DE_TAX_IDENTIFICATION_NUMBER = "DE Tax Identification Number"
    DE_VALUE_ADDED_NUMBER = "DE Value Added Number"
    DK_PERSONAL_IDENTIFICATION_NUMBER = "DK Personal Identification Number"
    DK_PERSONAL_IDENTIFICATION_V2 = "DK Personal Identification V2"
    DRUG_ENFORCEMENT_AGENCY_NUMBER = "Drug Enforcement Agency Number"
    EE_PERSONAL_IDENTIFICATION_CODE = "EE Personal Identification Code"
    EMAIL_ADDRESS = "Email"
    ESDNI = "ESDNI"
    ES_SOCIAL_SECURITY_NUMBER = "ES Social Security Number"
    ES_TAX_IDENTIFICATION_NUMBER = "ES Tax Identification Number"
    EUGPS_COORDINATES = "EU GPS Coordinates"
    EU_DEBIT_CARD_NUMBER = "EU Debit Card Number"
    EU_DRIVERS_LICENSE_NUMBER = "EU Drivers License Number"
    EU_NATIONAL_IDENTIFICATION_NUMBER = "EU National Identification Number"
    EU_PASSPORT_NUMBER = "EU Passport Number"
    EU_SOCIAL_SECURITY_NUMBER = "EU Social Security Number"
    EU_TAX_IDENTIFICATION_NUMBER = "EU Tax Identification Number"
    FI_EUROPEAN_HEALTH_NUMBER = "FI European Health Number"
    FI_NATIONAL_ID = "FI National ID"
    FI_NATIONAL_IDV2 = "FI National IDV2"
    FI_PASSPORT_NUMBER = "FI Passport Number"
    FR_DRIVERS_LICENSE_NUMBER = "FR Drivers License Number"
    FR_HEALTH_INSURANCE_NUMBER = "FR Health Insurance Number"
    FR_NATIONAL_ID = "FR National ID"
    FR_PASSPORT_NUMBER = "FR Passport Number"
    FR_SOCIAL_SECURITY_NUMBER = "FR Social Security Number"
    FR_TAX_IDENTIFICATION_NUMBER = "FR Tax Identification Number"
    FR_VALUE_ADDED_TAX_NUMBER = "FR Value Added Tax Number"
    GR_NATIONAL_IDV2 = "GR National ID V2"
    GR_NATIONAL_ID_CARD = "GR National ID Card"
    GR_TAX_IDENTIFICATION_NUMBER = "GR Tax Identification Number"
    HK_IDENTITY_CARD_NUMBER = "HK Identity Card Number"
    HR_IDENTITY_CARD_NUMBER = "HR Identity Card Number"
    HR_NATIONAL_ID_NUMBER = "HR National ID Number"
    HR_PERSONAL_IDENTIFICATION_NUMBER = "HR Personal Identification Number"
    HR_PERSONAL_IDENTIFICATION_OIB_NUMBER_V2 = (
        "HR Personal Identification OIB Number V2"
    )
    HU_PERSONAL_IDENTIFICATION_NUMBER = "HU Personal Identification Number"
    HU_TAX_IDENTIFICATION_NUMBER = "HU Tax Identification Number"
    HU_VALUE_ADDED_NUMBER = "HU Value Added Number"
    ID_IDENTITY_CARD_NUMBER = "ID Identity Card Number"
    IE_PERSONAL_PUBLIC_SERVICE_NUMBER = "IE Personal Public Service Number"
    IE_PERSONAL_PUBLIC_SERVICE_NUMBER_V2 = "IE Personal Public Service Number V2"
    IL_BANK_ACCOUNT_NUMBER = "IL Bank Account Number"
    IL_NATIONAL_ID = "IL National ID"
    INTERNATIONAL_BANKING_ACCOUNT_NUMBER = "International Banking Account Number"
    IN_PERMANENT_ACCOUNT = "IN Permanent Account"
    IN_UNIQUE_IDENTIFICATION_NUMBER = "IN Unique Identification Number"
    IP_ADDRESS = "IP Address"
    IT_DRIVERS_LICENSE_NUMBER = "IT Drivers License Number"
    IT_FISCAL_CODE = "IT Fiscal Code"
    IT_VALUE_ADDED_TAX_NUMBER = "IT Value Added Tax Number"
    JP_BANK_ACCOUNT_NUMBER = "JP Bank Account Number"
    JP_DRIVERS_LICENSE_NUMBER = "JP Drivers License Number"
    JP_MY_NUMBER_CORPORATE = "JP MyNumber Corporate"
    JP_MY_NUMBER_PERSONAL = "JP MyNumber Personal"
    JP_PASSPORT_NUMBER = "JP Passport Number"
    JP_RESIDENCE_CARD_NUMBER = "JP Residence Card Number"
    JP_RESIDENT_REGISTRATION_NUMBER = "JP Resident Registration Number"
    JP_SOCIAL_INSURANCE_NUMBER = "JP Social Insurance Number"
    KR_RESIDENT_REGISTRATION_NUMBER = "KR Resident Registration Number"
    LT_PERSONAL_CODE = "LT Personal Code"
    LU_NATIONAL_IDENTIFICATION_NUMBER_NATURAL = (
        "LU National Identification Number Natural"
    )
    LU_NATIONAL_IDENTIFICATION_NUMBER_NON_NATURAL = (
        "LU National Identification Number Non Natural"
    )
    LV_PERSONAL_CODE = "LV Personal Code"
    MT_IDENTITY_CARD_NUMBER = "MT Identity Card Number"
    MT_TAX_ID_NUMBER = "MT Tax ID Number"
    MY_IDENTITY_CARD_NUMBER = "MY Identity Card Number"
    NL_CITIZENS_SERVICE_NUMBER = "NL Citizens Service Number"
    NL_CITIZENS_SERVICE_NUMBER_V2 = "NL Citizens Service Number V2"
    NL_TAX_IDENTIFICATION_NUMBER = "NL Tax Identification Number"
    NL_VALUE_ADDED_TAX_NUMBER = "NL Value Added Tax Number"
    NO_IDENTITY_NUMBER = "NO Identity Number"
    NZ_BANK_ACCOUNT_NUMBER = "NZ Bank Account Number"
    NZ_DRIVERS_LICENSE_NUMBER = "NZ Drivers License Number"
    NZ_INLAND_REVENUE_NUMBER = "NZ Inland Revenue Number"
    NZ_MINISTRY_OF_HEALTH_NUMBER = "NZ Ministry Of Health Number"
    NZ_SOCIAL_WELFARE_NUMBER = "NZ Social Welfare Number"
    ORGANIZATION = "Organization"
    PERSON = "Person"
    PHONE_NUMBER = "Phone Number"
    PH_UNIFIED_MULTI_PURPOSE_ID_NUMBER = "PH Unified Multi Purpose ID Number"
    PLREGON_NUMBER = "PL REGON Number"
    PL_IDENTITY_CARD = "PL Identity Card"
    PL_NATIONAL_ID = "PL National ID"
    PL_NATIONAL_IDV2 = "PL National IDV2"
    PL_PASSPORT_NUMBER = "PL Passport Number"
    PL_TAX_IDENTIFICATION_NUMBER = "PL Tax Identification Number"
    PT_CITIZEN_CARD_NUMBER = "PT Citizen Card Number"
    PT_CITIZEN_CARD_NUMBER_V2 = "PT Citizen Card Number V2"
    PT_TAX_IDENTIFICATION_NUMBER = "PT Tax Identification Number"
    RO_PERSONAL_NUMERICAL_CODE = "RO Personal NumericalCode"
    RU_PASSPORT_NUMBER_DOMESTIC = "RU Passport Number Domestic"
    RU_PASSPORT_NUMBER_INTERNATIONAL = "RU Passport Number International"
    SA_NATIONAL_ID = "SA National ID"
    SE_NATIONAL_ID = "SE National ID"
    SE_NATIONAL_IDV2 = "SE National IDV2"
    SE_PASSPORT_NUMBER = "SE Passport Number"
    SE_TAX_IDENTIFICATION_NUMBER = "SE Tax Identification Number"
    SG_NATIONAL_REGISTRATION_IDENTITY_CARD_NUMBER = (
        "SG National Registration Identity Card Number"
    )
    SI_TAX_IDENTIFICATION_NUMBER = "SI Tax Identification Number"
    SI_UNIQUE_MASTER_CITIZEN_NUMBER = "SI Unique Master Citizen Number"
    SK_PERSONAL_NUMBER = "SK Personal Number"
    SQL_SERVER_CONNECTION_STRING = "SQL Server Connection String"
    SWIFT_CODE = "SWIFT Code"
    TH_POPULATION_IDENTIFICATION_CODE = "TH Population Identification Code"
    TR_NATIONAL_IDENTIFICATION_NUMBER = "TR National Identification Number"
    TW_NATIONAL_ID = "TW National ID"
    TW_PASSPORT_NUMBER = "TW Passport Number"
    TW_RESIDENT_CERTIFICATE = "TW Resident Certificate"
    UA_PASSPORT_NUMBER_DOMESTIC = "UA Passport Number Domestic"
    UA_PASSPORT_NUMBER_INTERNATIONAL = "UA Passport Number International"
    UK_DRIVERS_LICENSE_NUMBER = "UK Drivers License Number"
    UK_ELECTORAL_ROLL_NUMBER = "UK Electoral Roll Number"
    UK_NATIONAL_HEALTH_NUMBER = "UK National Health Number"
    UK_NATIONAL_INSURANCE_NUMBER = "UK National Insurance Number"
    UK_UNIQUE_TAXPAYER_NUMBER = "UK Unique Taxpayer Number"
    URL = "URL"
    USUK_PASSPORT_NUMBER = "US UK Passport Number"
    US_BANK_ACCOUNT_NUMBER = "US Bank Account Number"
    US_DRIVERS_LICENSE_NUMBER = "US Drivers License Number"
    US_INDIVIDUAL_TAXPAYER_IDENTIFICATION = "US Individual Taxpayer Identification"
    US_SOCIAL_SECURITY_NUMBER = "US Social Security Number"
    ZA_IDENTIFICATION_NUMBER = "ZA Identification Number"
