from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import List

import strawberry
from dataclasses_json import dataclass_json, LetterCase

# All listed PII Types from Milne et al (2018) and a few others along with
# models used for PII categorization for DHS, NIST, HIPAA, and the risk
# assessment models for reporting.


@dataclass_json(letter_case=LetterCase.CAMEL)
@strawberry.enum
class RiskLevel(Enum):
    LEVEL_ONE: int = 1  # Not-Identifiable
    LEVEL_TWO: int = 2  # Semi-Identifiable
    LEVEL_THREE: int = 3  # Identifiable


@dataclass_json(letter_case=LetterCase.CAMEL)
@strawberry.enum
class RiskLevelDefinition(Enum):
    LEVEL_ONE: str = "Non-Identifiable"  # Default if no entities were detected, risk level is set to this
    LEVEL_TWO: str = "Semi-Identifiable"
    LEVEL_THREE: str = "Identifiable"  # Level associated with Directly PII, PHI, and Standalone PII info types


@dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
@strawberry.type
class RiskAssessment:
    pii_type_detected: str
    risk_level: RiskLevel
    risk_level_definition: RiskLevelDefinition
    cluster_membership_type: ClusterMembershipType
    hipaa_category: HIPAACategory
    dhs_category: DHSCategory
    nist_category: NISTCategory


@dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
@strawberry.type
class RiskAssessmentList:
    risk_assessments: List[RiskAssessment]
    average_risk_score: float


@dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
@strawberry.type
class AnalysisResult:
    entity_type: str
    score: float
    start: int
    end: int
    risk_assessment: RiskAssessment


@dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
@strawberry.type
class AnalysisResultList:
    analysis_results: List[AnalysisResult]


@dataclass_json(letter_case=LetterCase.CAMEL)
@strawberry.enum
class PIIType(Enum):
    PHONE_NUMBER: str = "PHONE"
    WORK_PHONE_NUMBER: str = "PHONE"
    EMAIL_ADDRESS: str = "EMAIL"
    ABA_ROUTING_NUMBER: str = "ABA_ROUTING_NUMBER"
    IP_ADDRESS: str = "IP_ADDRESS"
    DATE: str = "DATE"
    ADDRESS: str = "ADDRESS"
    HOME_ADDRESS: str = "ADDRESS"
    WORK_ADDRESS: str = "ADDRESS"
    AGE: str = "AGE"
    PERSON: str = "PERSON"
    CREDIT_CARD_NUMBER: str = "CREDIT_CARD_NUMBER"
    CREDIT_SCORE: str = "CREDIT_SCORE"
    CRYPTO: str = "CRYPTO"
    URL: str = "URL"
    DATE_TIME: str = "DATE_TIME"
    LOCATION: str = "LOCATION"
    ZIPCODE: str = "ZIPCODE"
    RACE: str = "RACE"
    HEIGHT: str = "HEIGHT"
    WEIGHT: str = "WEIGHT"
    GENDER: str = "GENDER"
    HOMETOWN: str = "HOMETOWN"
    SCREEN_NAME: str = "SCREEN_NAME"
    MARITAL_STATUS: str = "MARITAL_STATUS"
    NUMBER_OF_CHILDREN: str = "NUMBER_OF_CHILDREN"
    RELIGION: str = "RELIGION"
    COUNTRY_OF_CITIZENSHIP: str = "COUNTRY_OF_CITIZENSHIP"
    VOICE_PRINT: str = "VOICE_PRINT"
    FINGERPRINT: str = "FINGERPRINT"
    DNA_PROFILE: str = "DNA_PROFILE"
    PICTURE_FACE: str = "PICTURE_FACE"
    HANDWRITING_SAMPLE: str = "HANDWRITING_SAMPLE"
    MOTHERS_MAIDEN_NAME: str = "MOTHERS_MAIDEN_NAME"
    DIGITAL_SIGNATURE: str = "DIGITAL_SIGNATURE"
    HEALTH_INSURANCE_ID: str = "HEALTH_INSURANCE_ID"
    SHOPPING_BEHAVIOR: str = "SHOPPING_BEHAVIOR"
    POLITICAL_AFFILIATION: str = "POLITICAL_AFFILIATION"
    SEXUAL_PREFERENCE: str = "SEXUAL_PREFERENCE"
    SOCIAL_NETWORK_PROFILE: str = "SOCIAL_NETWORK_PROFILE"
    JOB_TITLE: str = "JOB_TITLE"
    INCOME_LEVEL: str = "INCOME_LEVEL"
    OCCUPATION: str = "OCCUPATION"
    DOCUMENTS: str = "DOCUMENTS"
    LEGAL_DOCUMENTS: str = "LEGAL_DOCUMENTS"
    MEDICAL_LICENSE: str = "MEDICAL_LICENSE"
    LICENSE_PLATE_NUMBER: str = "LICENSE_PLATE_NUMBER"
    SECURITY_ACCESS_CODES: str = "SECURITY_ACCESS_CODES"
    PASSWORD: str = "PASSWORD"
    US_SOCIAL_SECURITY_NUMBER: str = "US_SOCIAL_SECURITY_NUMBER"
    US_BANK_ACCOUNT_NUMBER: str = "US_BANK_ACCOUNT_NUMBER"
    US_DRIVERS_LICENSE_NUMBER: str = "US_DRIVERS_LICENSE_NUMBER"
    US_PASSPORT_NUMBER: str = "US_PASSPORT_NUMBER"
    US_INDIVIDUAL_TAXPAYER_IDENTIFICATION: str = "US_INDIVIDUAL_TAXPAYER_IDENTIFICATION"
    UK_DRIVERS_LICENSE_NUMBER: str = "UK_DRIVERS_LICENSE_NUMBER"
    UK_ELECTORAL_ROLL_NUMBER: str = "UK_ELECTORAL_ROLL_NUMBER"
    UK_NATIONAL_HEALTH_NUMBER: str = "UK_NATIONAL_HEALTH_NUMBER"
    UK_NATIONAL_INSURANCE_NUMBER: str = "UK_NATIONAL_INSURANCE_NUMBER"
    UK_UNIQUE_TAXPAYER_NUMBER: str = "UK_UNIQUE_TAXPAYER_NUMBER"
    UK_PASSPORT_NUMBER: str = "UK_PASSPORT_NUMBER"
    INTERNATIONAL_BANKING_ACCOUNT_NUMBER: str = "INTERNATIONAL_BANKING_ACCOUNT_NUMBER"
    ES_TAX_IDENTIFICATION_NUMBER: str = "ES_TAX_IDENTIFICATION_NUMBER"
    SG_NATIONAL_REGISTRATION_IDENTITY_CARD_NUMBER: str = (
        "SG_NATIONAL_REGISTRATION_IDENTITY_CARD_NUMBER"
    )

    AR_NATIONAL_IDENTITY_NUMBER: str = "AR_NATIONAL_IDENTITY_NUMBER"
    AT_IDENTITY_CARD: str = "AT_IDENTITY_CARD"
    AT_TAX_IDENTIFICATION_NUMBER: str = "AT_TAX_IDENTIFICATION_NUMBER"
    AT_VALUE_ADDED_TAX_NUMBER: str = "AT_VALUE_ADDED_TAX_NUMBER"
    AU_BANK_ACCOUNT_NUMBER: str = "AU_BANK_ACCOUNT_NUMBER"
    AU_BUSINESS_NUMBER: str = "AU_BUSINESS_NUMBER"
    AU_COMPANY_NUMBER: str = "AU_COMPANY_NUMBER"
    AU_DRIVERS_LICENSE_NUMBER: str = "AU_DRIVERS_LICENSE_NUMBER"
    AU_MEDICAL_ACCOUNT_NUMBER: str = "AU_MEDICAL_ACCOUNT_NUMBER"
    AU_PASSPORT_NUMBER: str = "AU_PASSPORT_NUMBER"
    AU_TAX_FILE_NUMBER: str = "AU_TAX_FILE_NUMBER"
    BE_NATIONAL_NUMBER: str = "BE_NATIONAL_NUMBER"
    BE_NATIONAL_NUMBER_V2: str = "BE_NATIONAL_NUMBER_V2"
    BE_VALUE_ADDED_TAX_NUMBER: str = "BE_VALUE_ADDED_TAX_NUMBER"
    BG_UNIFORM_CIVIL_NUMBER: str = "BG_UNIFORM_CIVIL_NUMBER"
    BRCPF_NUMBER: str = "BRCPF_NUMBER"
    BR_LEGAL_ENTITY_NUMBER: str = "BR_LEGAL_ENTITY_NUMBER"
    BR_NATIONAL_IDRG: str = "BR_NATIONAL_IDRG"
    CA_BANK_ACCOUNT_NUMBER: str = "CA_BANK_ACCOUNT_NUMBER"
    CA_DRIVERS_LICENSE_NUMBER: str = "CA_DRIVERS_LICENSE_NUMBER"
    CA_HEALTH_SERVICE_NUMBER: str = "CA_HEALTH_SERVICE_NUMBER"
    CA_PASSPORT_NUMBER: str = "CA_PASSPORT_NUMBER"
    CA_PERSONAL_HEALTH_IDENTIFICATION: str = "CA_PERSONAL_HEALTH_IDENTIFICATION"
    CA_SOCIAL_INSURANCE_NUMBER: str = "CA_SOCIAL_INSURANCE_NUMBER"
    CH_SOCIAL_SECURITY_NUMBER: str = "CH_SOCIAL_SECURITY_NUMBER"
    CL_IDENTITY_CARD_NUMBER: str = "CL_IDENTITY_CARD_NUMBER"
    CN_RESIDENT_IDENTITY_CARD_NUMBER: str = "CN_RESIDENT_IDENTITY_CARD_NUMBER"
    CY_IDENTITY_CARD: str = "CY_IDENTITY_CARD"
    CY_TAX_IDENTIFICATION_NUMBER: str = "CY_TAX_IDENTIFICATION_NUMBER"
    CZ_PERSONAL_IDENTITY_NUMBER: str = "CZ_PERSONAL_IDENTITY_NUMBER"
    CZ_PERSONAL_IDENTITY_V2: str = "CZ_PERSONAL_IDENTITY_V2"
    DE_DRIVERS_LICENSE_NUMBER: str = "DE_DRIVERS_LICENSE_NUMBER"
    DE_IDENTITY_CARD_NUMBER: str = "DE_IDENTITY_CARD_NUMBER"
    DE_PASSPORT_NUMBER: str = "DE_PASSPORT_NUMBER"
    DE_TAX_IDENTIFICATION_NUMBER: str = "DE_TAX_IDENTIFICATION_NUMBER"
    DE_VALUE_ADDED_NUMBER: str = "DE_VALUE_ADDED_NUMBER"
    DK_PERSONAL_IDENTIFICATION_NUMBER: str = "DK_PERSONAL_IDENTIFICATION_NUMBER"
    DK_PERSONAL_IDENTIFICATION_V2: str = "DK_PERSONAL_IDENTIFICATION_V2"
    DRUG_ENFORCEMENT_AGENCY_NUMBER: str = "DRUG_ENFORCEMENT_AGENCY_NUMBER"
    EE_PERSONAL_IDENTIFICATION_CODE: str = "EE_PERSONAL_IDENTIFICATION_CODE"
    ESDNI: str = "ESDNI"
    ES_SOCIAL_SECURITY_NUMBER: str = "ES_SOCIAL_SECURITY_NUMBER"
    EUGPS_COORDINATES: str = "EUGPS_COORDINATES"
    EU_DEBIT_CARD_NUMBER: str = "EU_DEBIT_CARD_NUMBER"
    EU_DRIVERS_LICENSE_NUMBER: str = "EU_DRIVERS_LICENSE_NUMBER"
    EU_NATIONAL_IDENTIFICATION_NUMBER: str = "EU_NATIONAL_IDENTIFICATION_NUMBER"
    EU_PASSPORT_NUMBER: str = "EU_PASSPORT_NUMBER"
    EU_SOCIAL_SECURITY_NUMBER: str = "EU_SOCIAL_SECURITY_NUMBER"
    EU_TAX_IDENTIFICATION_NUMBER: str = "EU_TAX_IDENTIFICATION_NUMBER"
    FI_EUROPEAN_HEALTH_NUMBER: str = "FI_EUROPEAN_HEALTH_NUMBER"
    FI_NATIONAL_ID: str = "FI_NATIONAL_ID"
    FI_NATIONAL_IDV2: str = "FI_NATIONAL_IDV2"
    FI_PASSPORT_NUMBER: str = "FI_PASSPORT_NUMBER"
    FR_DRIVERS_LICENSE_NUMBER: str = "FR_DRIVERS_LICENSE_NUMBER"
    FR_HEALTH_INSURANCE_NUMBER: str = "FR_HEALTH_INSURANCE_NUMBER"
    FR_NATIONAL_ID: str = "FR_NATIONAL_ID"
    FR_PASSPORT_NUMBER: str = "FR_PASSPORT_NUMBER"
    FR_SOCIAL_SECURITY_NUMBER: str = "FR_SOCIAL_SECURITY_NUMBER"
    FR_TAX_IDENTIFICATION_NUMBER: str = "FR_TAX_IDENTIFICATION_NUMBER"
    FR_VALUE_ADDED_TAX_NUMBER: str = "FR_VALUE_ADDED_TAX_NUMBER"
    GR_NATIONAL_IDV2: str = "GR_NATIONAL_IDV2"
    GR_NATIONAL_ID_CARD: str = "GR_NATIONAL_ID_CARD"
    GR_TAX_IDENTIFICATION_NUMBER: str = "GR_TAX_IDENTIFICATION_NUMBER"
    HK_IDENTITY_CARD_NUMBER: str = "HK_IDENTITY_CARD_NUMBER"
    HR_IDENTITY_CARD_NUMBER: str = "HR_IDENTITY_CARD_NUMBER"
    HR_NATIONAL_ID_NUMBER: str = "HR_NATIONAL_ID_NUMBER"
    HR_PERSONAL_IDENTIFICATION_NUMBER: str = "HR_PERSONAL_IDENTIFICATION_NUMBER"
    HR_PERSONAL_IDENTIFICATION_OIB_NUMBER_V2: str = (
        "HR_PERSONAL_IDENTIFICATION_OIB_NUMBER_V2"
    )
    HU_PERSONAL_IDENTIFICATION_NUMBER: str = "HU_PERSONAL_IDENTIFICATION_NUMBER"
    HU_TAX_IDENTIFICATION_NUMBER: str = "HU_TAX_IDENTIFICATION_NUMBER"
    HU_VALUE_ADDED_NUMBER: str = "HU_VALUE_ADDED_NUMBER"
    ID_IDENTITY_CARD_NUMBER: str = "ID_IDENTITY_CARD_NUMBER"
    IE_PERSONAL_PUBLIC_SERVICE_NUMBER: str = "IE_PERSONAL_PUBLIC_SERVICE_NUMBER"
    IE_PERSONAL_PUBLIC_SERVICE_NUMBER_V2: str = "IE_PERSONAL_PUBLIC_SERVICE_NUMBER_V2"
    IL_BANK_ACCOUNT_NUMBER: str = "IL_BANK_ACCOUNT_NUMBER"
    IL_NATIONAL_ID: str = "IL_NATIONAL_ID"
    IN_PERMANENT_ACCOUNT: str = "INPermanentAccount"
    IN_UNIQUE_IDENTIFICATION_NUMBER: str = "INUniqueIdentificationNumber"
    IT_DRIVERS_LICENSE_NUMBER: str = "IT_DRIVERS_LICENSE_NUMBER"
    IT_FISCAL_CODE: str = "IT_FISCAL_CODE"
    IT_VALUE_ADDED_TAX_NUMBER: str = "IT_VALUE_ADDED_TAX_NUMBER"
    JP_BANK_ACCOUNT_NUMBER: str = "JP_BANK_ACCOUNT_NUMBER"
    JP_DRIVERS_LICENSE_NUMBER: str = "JP_DRIVERS_LICENSE_NUMBER"
    JP_MY_NUMBER_CORPORATE: str = "JP_MY_NUMBER_CORPORATE"
    JP_MY_NUMBER_PERSONAL: str = "JP_MY_NUMBER_PERSONAL"
    JP_PASSPORT_NUMBER: str = "JP_PASSPORT_NUMBER"
    JP_RESIDENCE_CARD_NUMBER: str = "JP_RESIDENCE_CARD_NUMBER"
    JP_RESIDENT_REGISTRATION_NUMBER: str = "JP_RESIDENT_REGISTRATION_NUMBER"
    JP_SOCIAL_INSURANCE_NUMBER: str = "JP_SOCIAL_INSURANCE_NUMBER"
    KR_RESIDENT_REGISTRATION_NUMBER: str = "KR_RESIDENT_REGISTRATION_NUMBER"
    LT_PERSONAL_CODE: str = "LT_PERSONAL_CODE"
    LU_NATIONAL_IDENTIFICATION_NUMBER_NATURAL: str = (
        "LU_NATIONAL_IDENTIFICATION_NUMBER_NATURAL"
    )
    LU_NATIONAL_IDENTIFICATION_NUMBER_NON_NATURAL: str = (
        "LU_NATIONAL_IDENTIFICATION_NUMBER_NON_NATURAL"
    )
    LV_PERSONAL_CODE: str = "LV_PERSONAL_CODE"
    MT_IDENTITY_CARD_NUMBER: str = "MT_IDENTITY_CARD_NUMBER"
    MT_TAX_ID_NUMBER: str = "MT_TAX_ID_NUMBER"
    MY_IDENTITY_CARD_NUMBER: str = "MY_IDENTITY_CARD_NUMBER"
    NL_CITIZENS_SERVICE_NUMBER: str = "NL_CITIZENS_SERVICE_NUMBER"
    NL_CITIZENS_SERVICE_NUMBER_V2: str = "NL_CITIZENS_SERVICE_NUMBER_V2"
    NL_TAX_IDENTIFICATION_NUMBER: str = "NL_TAX_IDENTIFICATION_NUMBER"
    NL_VALUE_ADDED_TAX_NUMBER: str = "NL_VALUE_ADDED_TAX_NUMBER"
    NO_IDENTITY_NUMBER: str = "NO_IDENTITY_NUMBER"
    NZ_BANK_ACCOUNT_NUMBER: str = "NZ_BANK_ACCOUNT_NUMBER"
    NZ_DRIVERS_LICENSE_NUMBER: str = "NZ_DRIVERS_LICENSE_NUMBER"
    NZ_INLAND_REVENUE_NUMBER: str = "NZ_INLAND_REVENUE_NUMBER"
    NZ_MINISTRY_OF_HEALTH_NUMBER: str = "NZ_MINISTRY_OF_HEALTH_NUMBER"
    NZ_SOCIAL_WELFARE_NUMBER: str = "NZ_SOCIAL_WELFARE_NUMBER"
    PH_UNIFIED_MULTI_PURPOSE_ID_NUMBER: str = "PH_UNIFIED_MULTI_PURPOSE_ID_NUMBER"
    PLREGON_NUMBER: str = "PLREGON_NUMBER"
    PL_IDENTITY_CARD: str = "PL_IDENTITY_CARD"
    PL_NATIONAL_ID: str = "PL_NATIONAL_ID"
    PL_NATIONAL_IDV2: str = "PL_NATIONAL_IDV2"
    PL_PASSPORT_NUMBER: str = "PL_PASSPORT_NUMBER"
    PL_TAX_IDENTIFICATION_NUMBER: str = "PL_TAX_IDENTIFICATION_NUMBER"
    PT_CITIZEN_CARD_NUMBER: str = "PT_CITIZEN_CARD_NUMBER"
    PT_CITIZEN_CARD_NUMBER_V2: str = "PT_CITIZEN_CARD_NUMBER_V2"
    PT_TAX_IDENTIFICATION_NUMBER: str = "PT_TAX_IDENTIFICATION_NUMBER"
    RO_PERSONAL_NUMERICAL_CODE: str = "RO_PERSONAL_NUMERICAL_CODE"
    RU_PASSPORT_NUMBER_DOMESTIC: str = "RU_PASSPORT_NUMBER_DOMESTIC"
    RU_PASSPORT_NUMBER_INTERNATIONAL: str = "RU_PASSPORT_NUMBER_INTERNATIONAL"
    SA_NATIONAL_ID: str = "SA_NATIONAL_ID"
    SE_NATIONAL_ID: str = "SE_NATIONAL_ID"
    SE_NATIONAL_IDV2: str = "SE_NATIONAL_IDV2"
    SE_PASSPORT_NUMBER: str = "SE_PASSPORT_NUMBER"
    SE_TAX_IDENTIFICATION_NUMBER: str = "SE_TAX_IDENTIFICATION_NUMBER"
    SI_TAX_IDENTIFICATION_NUMBER: str = "SI_TAX_IDENTIFICATION_NUMBER"
    SI_UNIQUE_MASTER_CITIZEN_NUMBER: str = "SI_UNIQUE_MASTER_CITIZEN_NUMBER"
    SK_PERSONAL_NUMBER: str = "SK_PERSONAL_NUMBER"
    SWIFT_CODE: str = "SWIFT_CODE"
    TH_POPULATION_IDENTIFICATION_CODE: str = "TH_POPULATION_IDENTIFICATION_CODE"
    TR_NATIONAL_IDENTIFICATION_NUMBER: str = "TR_NATIONAL_IDENTIFICATION_NUMBER"
    TW_NATIONAL_ID: str = "TW_NATIONAL_ID"
    TW_PASSPORT_NUMBER: str = "TW_PASSPORT_NUMBER"
    TW_RESIDENT_CERTIFICATE: str = "TW_RESIDENT_CERTIFICATE"
    UA_PASSPORT_NUMBER_DOMESTIC: str = "UA_PASSPORT_NUMBER_DOMESTIC"
    UA_PASSPORT_NUMBER_INTERNATIONAL: str = "UA_PASSPORT_NUMBER_INTERNATIONAL"
    ZA_IDENTIFICATION_NUMBER: str = "ZA_IDENTIFICATION_NUMBER"


@dataclass_json(letter_case=LetterCase.CAMEL)
@strawberry.enum
class NISTCategory(Enum):
    LINKABLE: str = "Linkable"
    DIRECTLY_PII: str = "Directly PII"


@dataclass_json(letter_case=LetterCase.CAMEL)
@strawberry.enum
class DHSCategory(Enum):
    NOT_MENTIONED: str = "Not Mentioned"
    LINKABLE: str = "Linkable"
    STAND_ALONE_PII: str = "Stand Alone PII"


@dataclass_json(letter_case=LetterCase.CAMEL)
@strawberry.enum
class HIPAACategory(Enum):
    NON_PHI: str = "Not Protected Health Information"
    PHI: str = "Protected Health Information"


@dataclass_json(letter_case=LetterCase.CAMEL)
@strawberry.enum
class ClusterMembershipType(Enum):
    BASIC_DEMOGRAPHICS: str = "Basic Demographics"
    PERSONAL_PREFERENCES: str = "Personal Preferences"
    CONTACT_INFORMATION: str = "Contact Information"
    COMMUNITY_INTERACTION: str = "Community Interaction"
    FINANCIAL_INFORMATION: str = "Financial Information"
    SECURE_IDENTIFIERS: str = "Secure Identifiers"
