# Creates a new tag and GitHub release based on the output of poetry version
name: Tag

on:
  workflow_dispatch:

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Checkout branch "main"
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Install Global Dependencies
        run: pip install -U pip && pip install poetry wheel
      - name: Build project for distribution
        run: poetry build
      - name: Get Version
        id: get_version
        run: |
          TAG_NAME=$(poetry version -s)
          echo "::set-output name=tag_name::$TAG_NAME"
          echo "$TAG_NAME"
      - name: Create Tag
        uses: actions/github-script@v3
        env:
           TAG: v${{ steps.get_version.outputs.tag_name }}
        with:
           github-token: ${{ github.token }}
           script: |
             github.git.createRef({
               owner: context.repo.owner,
               repo: context.repo.repo,
              ref: "refs/tags/${{ steps.get_version.outputs.tag_name }}",
               sha: context.sha
             })