name: Tag

on:
  workflow_dispatch:
    inputs:
      version_type_override:
        required: false
        type: choice
        description: (Optional) override the version type
        default: (unset)
        options:
          - (unset)
          - patch
          - minor
          - major

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: set $VERSION_TYPE
        run: |
          if [[ ("${{ github.event.inputs.version_type_override }}" == "") || ("${{ github.event.inputs.version_type_override }}" == "(unset)") ]]; then
            VERSION_TYPE=patch
          else
            VERSION_TYPE=${{ github.event.inputs.version_type_override }}
          fi
          echo "VERSION_TYPE=$VERSION_TYPE" >> $GITHUB_ENV
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout branch "main"
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Release snapshot
        id: release-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION_TYPE }}
          release_name: v${{ env.VERSION_TYPE }}
          draft: false
          prerelease: false